# Generated by Django 3.0.5 on 2021-10-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='json_details_file',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='tx',
        ),
    ]
