# Generated by Django 3.0.5 on 2021-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211025_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='json_details_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='auction',
            name='tx',
            field=models.CharField(default='', max_length=256),
        ),
    ]
