# Generated by Django 3.0.5 on 2021-11-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211025_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='close_data',
            new_name='close_date',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='open_data',
            new_name='open_date',
        ),
    ]
